### ISSUE TITLE
Launching Problem in windows

### ISSUE THREAD

**Issue by prabal-rawal** [ObaraEmmanuel/Formation#10]
After installing with pip command, the formation studio does not launch. 

Commands tried: "formation-studio" and "python -m formation-studio".
![image](https://user-images.githubusercontent.com/74870456/120968067-01857280-c786-11eb-8a78-506a0c0fbe7b.png)
![image](https://user-images.githubusercontent.com/74870456/120968110-13ffac00-c786-11eb-827f-e0cffd190c5e.png)

Python Version: 3.8

**Comment by ObaraEmmanuel** [comment]
Do you have more than one python version installed? If so, you need to make sure pip installs to the right version. Otherwise  sometimes you might need to pip install as administrator. You can try uninstalling
```
pip uninstall formation-studio
```
then reinstall as administrator.

Could you send a screenshot of what was displayed on the console when you tried installing it the first time?

**Comment by prabal-rawal** [comment]
I do not have the ss of when I first installed but my PC currently have only one version of python i.e 3.8

**Comment by prabal-rawal** [comment]
Can u possibly check  if it is a bug in 3.8 by installing it in a virtual env??

**Comment by prabal-rawal** [comment]
I uninstalled it and then reinstalled it running through administration in cmd.
It works now.
Thanks
