### ISSUE TITLE
Sun Valley Integration

### ISSUE THREAD

**Issue by abe-mart** [ObaraEmmanuel/Formation#14]
Cool project!  Is it possible to use this together with the Sun Valley theme?  I feel like the combination of an easy drag and drop builder with modern-looking output is a major gap in Python UI tools right now.  https://github.com/rdbende/Sun-Valley-ttk-theme

**Comment by ObaraEmmanuel** [comment]
[Sun-Valley-ttk-theme](https://github.com/rdbende/Sun-Valley-ttk-theme) is really cool. I can definitely add support. I have been planning to add support for ttk themes but I have never deceided on the way to go given the complexities involved. The first concern is that the studio itself has to be immune to ttk theme changes by the user given its also written in tkinter. So far, only the scrollbars will be affected since they are the only ttk widgets I use and I think I can allow it. We can discuss further with [rdbende](https://github.com/rdbende) if I can get a hold of him. @abe-mart if you have any more ideas on this and any other thing feel free to share.

**Comment by abe-mart** [comment]
Awesome!  Personally, I think the ability to drag and drop a beautiful GUI in Python would really be a game-changer.  I've been looking on and off for the last six months, and haven't found anything out there that really quite fills that space.  I saw that @rdbende has a couple of other nice themes as well, Azure and Forest, though I think Sun Valley is my favorite of the three.  I for one wouldn't mind if the studio scrollbars changed colors.

**Comment by ObaraEmmanuel** [comment]
@abe-mart I finally got round to adding support for this. It's been long I know but better late than never.
