### ISSUE TITLE
[FEATURE] Fonts for Buttons/checkbuttons/labels

### ISSUE THREAD

**Issue by mrx23dot** [ObaraEmmanuel/Formation#54]
My other OS resizes fonts for Buttons/checkbuttons/labels

![image](https://github.com/user-attachments/assets/78a5f5e8-887b-4f0e-84eb-79f9f6e0b9b5)

vs desired
![image](https://github.com/user-attachments/assets/371307c9-596c-4c47-874b-6fa541fc82da)

For **labels** shouldn't the app include **attr:font** in xml? 
Since there is default already selected:
![image](https://github.com/user-attachments/assets/87502ac4-aae6-417b-b378-24ce9e949473)
Or might need a checkbox saying let the system decide. 

For **Buttons**/**checkbuttons** there is no font option, is that correct?
At least there should be an option to fixate what we see in editor, to prevent OS overriding it, basd on GPT:
button = tk.Button(root, text="Fixed Text", width=10, **font=fixed_font**, padx=5, pady=5)

**Comment by ObaraEmmanuel** [comment]
The `attr:font` is not there in the XML because the default value has not been changed. Only attributes that have been explicitly changed go into the XML. The font input is showing the first item on the list (Arial) because `TKDefaultFont` is not part of the list (probably something I should fix)

If you want the font to be consistent you are going to have to explicitly set it because what you are seeing here is the default behavior of `TkDefaultFont`. The problem is you are using place layout manager which will not adjust widget size to fit the font. There is really nothing to fix or add here except for the font input displaying the wrong font.

**Comment by ObaraEmmanuel** [comment]
For `ttk` widgets most attributes will not be available because `ttk` uses themes.

**Comment by ObaraEmmanuel** [comment]
> Might be better to put legacy first and default since it's more deterministic:

I agree. I will do that.
